#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASSWD}';
    CREATE DATABASE ${APP_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_USER} TO ${APP_DB};
EOSQL
