# Generated by Django 2.0.1 on 2018-01-31 21:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('QuizSite', '0002_auto_20180131_2031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='NULL', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quiz',
            field=models.TextField(max_length=10000),
        ),
    ]
