# Generated by Django 2.0.2 on 2018-03-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizSite', '0005_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FL', 'Зарубіжна Література'), ('PY', 'Психологія'), ('EN', 'Англійська мова'), ('DE', 'Німецька мова')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='quiz',
            field=models.TextField(max_length=4000),
        ),
    ]
