# Generated by Django 2.0.2 on 2018-03-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizSite', '0007_auto_20180323_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizSite.Categories', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
    ]
