# Generated by Django 2.0.2 on 2018-03-25 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuizSite', '0009_auto_20180323_2233'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
